[2023-06-05T22:02:42.028+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: process_weather_people_postgres.group_users.load_1_user_into_table scheduled__2023-06-04T00:00:00+00:00 [queued]>
[2023-06-05T22:02:42.039+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: process_weather_people_postgres.group_users.load_1_user_into_table scheduled__2023-06-04T00:00:00+00:00 [queued]>
[2023-06-05T22:02:42.040+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-06-05T22:02:42.040+0000] {taskinstance.py:1363} INFO - Starting attempt 4 of 6
[2023-06-05T22:02:42.040+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-06-05T22:02:42.054+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): group_users.load_1_user_into_table> on 2023-06-04 00:00:00+00:00
[2023-06-05T22:02:42.063+0000] {standard_task_runner.py:55} INFO - Started process 7707 to run task
[2023-06-05T22:02:42.066+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'process_weather_people_postgres', 'group_users.load_1_user_into_table', 'scheduled__2023-06-04T00:00:00+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/process_weather_people_postgres/process_weather_people_postgres.py', '--cfg-path', '/tmp/tmpn0uiol4d']
[2023-06-05T22:02:42.067+0000] {standard_task_runner.py:83} INFO - Job 95: Subtask group_users.load_1_user_into_table
[2023-06-05T22:02:42.125+0000] {task_command.py:376} INFO - Running <TaskInstance: process_weather_people_postgres.group_users.load_1_user_into_table scheduled__2023-06-04T00:00:00+00:00 [running]> on host 1160da0dacdb
[2023-06-05T22:02:42.191+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=data_eng
AIRFLOW_CTX_DAG_ID=process_weather_people_postgres
AIRFLOW_CTX_TASK_ID=group_users.load_1_user_into_table
AIRFLOW_CTX_EXECUTION_DATE=2023-06-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-04T00:00:00+00:00
[2023-06-05T22:02:42.193+0000] {postgres.py:129} INFO - Running copy expert: COPY bronze.user FROM STDIN, filename: /tmp/user_inputt_1.csv
[2023-06-05T22:02:42.203+0000] {base.py:71} INFO - Using connection ID 'postgres_default' for task execution.
[2023-06-05T22:02:42.241+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/process_weather_people_postgres/functions/load_user_into_table.py", line 12, in load_user_into_table
    pg_hook.bulk_load(context["templates_dict"]["table_name"], file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 151, in bulk_load
    self.copy_expert(f"COPY {table} FROM STDIN", tmp_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 137, in copy_expert
    cur.copy_expert(sql, file)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type integer: ""
CONTEXT:  COPY user, line 1, column user_id: ""

[2023-06-05T22:02:42.250+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=process_weather_people_postgres, task_id=group_users.load_1_user_into_table, execution_date=20230604T000000, start_date=20230605T220242, end_date=20230605T220242
[2023-06-05T22:02:42.263+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 95 for task group_users.load_1_user_into_table (invalid input syntax for type integer: ""
CONTEXT:  COPY user, line 1, column user_id: ""
; 7707)
[2023-06-05T22:02:42.278+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-06-05T22:02:42.305+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
