[2023-06-05T21:53:34.511+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: process_weather_people_postgres.group_users.load_1_user_into_table scheduled__2023-06-04T00:00:00+00:00 [queued]>
[2023-06-05T21:53:34.525+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: process_weather_people_postgres.group_users.load_1_user_into_table scheduled__2023-06-04T00:00:00+00:00 [queued]>
[2023-06-05T21:53:34.526+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-06-05T21:53:34.526+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 4
[2023-06-05T21:53:34.526+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-06-05T21:53:34.542+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): group_users.load_1_user_into_table> on 2023-06-04 00:00:00+00:00
[2023-06-05T21:53:34.627+0000] {standard_task_runner.py:55} INFO - Started process 7251 to run task
[2023-06-05T21:53:34.632+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'process_weather_people_postgres', 'group_users.load_1_user_into_table', 'scheduled__2023-06-04T00:00:00+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/process_weather_people_postgres/process_weather_people_postgres.py', '--cfg-path', '/tmp/tmp36rblcd0']
[2023-06-05T21:53:34.634+0000] {standard_task_runner.py:83} INFO - Job 86: Subtask group_users.load_1_user_into_table
[2023-06-05T21:53:34.719+0000] {task_command.py:376} INFO - Running <TaskInstance: process_weather_people_postgres.group_users.load_1_user_into_table scheduled__2023-06-04T00:00:00+00:00 [running]> on host 1160da0dacdb
[2023-06-05T21:53:34.793+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=data_eng
AIRFLOW_CTX_DAG_ID=process_weather_people_postgres
AIRFLOW_CTX_TASK_ID=group_users.load_1_user_into_table
AIRFLOW_CTX_EXECUTION_DATE=2023-06-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-04T00:00:00+00:00
[2023-06-05T21:53:34.794+0000] {postgres.py:129} INFO - Running copy expert: COPY bronze.user FROM STDIN, filename: /tmp/user_input_1.csv
[2023-06-05T21:53:34.805+0000] {base.py:71} INFO - Using connection ID 'postgres_default' for task execution.
[2023-06-05T21:53:34.832+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/process_weather_people_postgres/functions/load_user_into_table.py", line 12, in load_user_into_table
    pg_hook.bulk_load(context["templates_dict"]["table_name"], file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 151, in bulk_load
    self.copy_expert(f"COPY {table} FROM STDIN", tmp_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 137, in copy_expert
    cur.copy_expert(sql, file)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type integer: ""
CONTEXT:  COPY user, line 1, column user_id: ""

[2023-06-05T21:53:34.842+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=process_weather_people_postgres, task_id=group_users.load_1_user_into_table, execution_date=20230604T000000, start_date=20230605T215334, end_date=20230605T215334
[2023-06-05T21:53:34.857+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 86 for task group_users.load_1_user_into_table (invalid input syntax for type integer: ""
CONTEXT:  COPY user, line 1, column user_id: ""
; 7251)
[2023-06-05T21:53:34.884+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-06-05T21:53:34.914+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
